### ISSUE TITLE
This website needs a favicon

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/hacktoberfest#6]
It's using the default Vue.js favicon right now. We should customize it. My suggestions, in order:

- orbtoberfest related icon
- hacktoberfest icon
- the normal CircleCI favicon

**Comment by gagandeepp** [comment]
can you please add hacktoberfest or orbtoberfest label to this isssue?
I can look into this

**Comment by felicianotech** [comment]
I will but please keep in mind that Hacktoberfest doesn't start until October 1st.

**Comment by gagandeepp** [comment]
please assign this to me

**Comment by KyleTryon** [comment]
Notes here for development. The favicon.ico file has been replaced with the CircleCI ico file as per the vue docs, I am not actually sure where the current ico file is coming from.
https://hacktoberfest.circleci.com/favicon.ico


Taking a look at the network tab in dev tools it looks like its coming from: https://hacktoberfest.circleci.com/img/icons/favicon-32x32.png

**Comment by Nelias** [comment]
It has been changed in the public folder but not in the dist folder that is why it was coming from there. In general the `dist` folder should be added to `.gitignore` file and generated based on the `public` folder only when the app is run. At the moment it has to be changed in both places as I did in #19

**Comment by KyleTryon** [comment]
Re-opening. The change in the PR only allows for a temporary change via the /dist folder. permanent changes must occur in the /src folder.

**Comment by hurnhu** [comment]
@KyleTryon check my PR, its a fix for it in the vue.config.js

**Comment by Nelias** [comment]
In Chrome where I opened the website before (https://hacktoberfest.circleci.com) I still have the default Vue favicon simply because it is cached in the browser's memory. In Safari where I never opened it before the favicon comes from the static (not generated) public folder and it is displayed correctly as Orbtoberfest graphic. New favicon also works in my phone's Chrome browser and Samsung Internet browser. It is also displayed correctly when I add it to my homescreen (PWA feature).

![image](https://user-images.githubusercontent.com/23236940/66113079-5f82af80-e5cc-11e9-915c-111abdee962f.png)
